export const sonySeries = {
	DSLR: 240,
	DSL5: 241,
	DSLT: 242,
	ILC1: 243,
	ILC2: 244,
	ILC3: 245
} as const;

export type Status = (typeof sonySeries)[keyof typeof sonySeries];

export const sonyModels: Record<string, { name: string; type: number }> = {
	// Supported Sony Models
	'DSLR-A230': { name: 'A230', type: sonySeries.DSLR },
	'DSLR-A290': { name: 'A290', type: sonySeries.DSLR },
	'DSLR-A330': { name: 'A330', type: sonySeries.DSLR },
	'DSLR-A380': { name: 'A380', type: sonySeries.DSLR },
	'DSLR-A390': { name: 'A390', type: sonySeries.DSLR },
	'DSLR-A450': { name: 'A450', type: sonySeries.DSL5 },
	'DSLR-A500': { name: 'A500', type: sonySeries.DSL5 },
	'DSLR-A550': { name: 'A550', type: sonySeries.DSL5 },
	'DSLR-A560': { name: 'A560', type: sonySeries.DSLT },
	'DSLR-A580': { name: 'A580', type: sonySeries.DSLT },
	'DSLR-A850': { name: 'A850', type: sonySeries.DSLR },
	'DSLR-A900': { name: 'A900', type: sonySeries.DSLR },
	'NEX-3': { name: 'NEX 3', type: sonySeries.DSLT },
	'NEX-C3': { name: 'NEX C3', type: sonySeries.DSLT },
	'NEX-F3': { name: 'NEX F3', type: sonySeries.ILC1 },
	'NEX-3N': { name: 'NEX 3N', type: sonySeries.ILC1 },
	'NEX-5': { name: 'NEX 5', type: sonySeries.DSLT },
	'NEX-5N': { name: 'NEX 5N', type: sonySeries.ILC1 },
	'NEX-5R': { name: 'NEX 5R', type: sonySeries.ILC1 },
	'NEX-5T': { name: 'NEX 5T', type: sonySeries.ILC1 },
	'NEX-6': { name: 'NEX 6', type: sonySeries.ILC1 },
	'NEX-7': { name: 'NEX 7', type: sonySeries.ILC1 },
	'SLT-A33': { name: 'A 33', type: sonySeries.DSLT },
	'SLT-A35': { name: 'A 35', type: sonySeries.DSLT },
	'SLT-A37': { name: 'A 37', type: sonySeries.ILC1 },
	'SLT-A55': { name: 'A 55', type: sonySeries.DSLT },
	'SLT-A55V': { name: 'A 55V', type: sonySeries.DSLT },
	'SLT-A57': { name: 'A 57', type: sonySeries.ILC1 },
	'SLT-A58': { name: 'A 58', type: sonySeries.ILC1 },
	'SLT-A65': { name: 'A 65', type: sonySeries.ILC1 },
	'SLT-A65V': { name: 'A 65V', type: sonySeries.ILC1 },
	'ILCA-68': { name: 'A 68', type: sonySeries.ILC1 },
	'SLT-A77': { name: 'A 77', type: sonySeries.ILC1 },
	'SLT-A77V': { name: 'A 77V', type: sonySeries.ILC1 },
	'ILCA-77M2': { name: 'A 77 II', type: sonySeries.ILC1 },
	'SLT-A99': { name: 'A 99', type: sonySeries.ILC1 },
	'SLT-A99V': { name: 'A 99V', type: sonySeries.ILC1 },
	'ILCA-99M2': { name: 'A 99 II', type: sonySeries.ILC1 },
	'ILCE-3000': { name: 'A 3000', type: sonySeries.ILC1 },
	'ILCE-3500': { name: 'A 3500', type: sonySeries.ILC1 },
	'ILCE-5000': { name: 'A 5000', type: sonySeries.ILC1 },
	'ILCE-5100': { name: 'A 5100', type: sonySeries.ILC1 },
	'ILCE-6000': { name: 'A 6000', type: sonySeries.ILC1 },
	'ILCE-6001': { name: 'A 6000', type: sonySeries.ILC1 },
	'ILCE-6100': { name: 'A 6100', type: sonySeries.ILC2 },
	'ILCE-6300': { name: 'A 6300', type: sonySeries.ILC2 },
	'ILCE-6400': { name: 'A 6400', type: sonySeries.ILC2 },
	'ILCE-6500': { name: 'A 6500', type: sonySeries.ILC2 },
	'ILCE-6600': { name: 'A 6600', type: sonySeries.ILC2 },
	'ILCE-6700': { name: 'A 6700', type: sonySeries.ILC3 },
	'ILCE-7C': { name: 'A 7c', type: sonySeries.ILC2 },
	'ILCE-7CM2': { name: 'A 7c II', type: sonySeries.ILC3 },
	'ILCE-7CR': { name: 'A 7cR', type: sonySeries.ILC3 },
	'ILCE-7': { name: 'A 7', type: sonySeries.ILC1 },
	'ILCE-7M2': { name: 'A 7 II', type: sonySeries.ILC1 },
	'ILCE-7M3': { name: 'A 7 III', type: sonySeries.ILC2 },
	'ILCE-7M4': { name: 'A 7 IV', type: sonySeries.ILC2 },
	'ILCE-7M4A': { name: 'A 7 IVa', type: sonySeries.ILC2 },
	'ILCE-7R': { name: 'A 7R', type: sonySeries.ILC1 },
	'ILCE-7RM2': { name: 'A 7R II', type: sonySeries.ILC2 },
	'ILCE-7RM3': { name: 'A 7R III', type: sonySeries.ILC2 },
	'ILCE-7RM3A': { name: 'A 7R IIIa', type: sonySeries.ILC2 },
	'ILCE-7RM4': { name: 'A 7R IV', type: sonySeries.ILC2 },
	'ILCE-7RM4A': { name: 'A 7R IVa', type: sonySeries.ILC2 },
	'ILCE-7RM5': { name: 'A 7R V', type: sonySeries.ILC2 },
	'ILCE-7S': { name: 'A 7S', type: sonySeries.ILC1 },
	'ILCE-7SM2': { name: 'A 7S II', type: sonySeries.ILC2 },
	'ILCE-7SM3': { name: 'A 7S III', type: sonySeries.ILC2 },
	'ILCE-9': { name: 'A 9', type: sonySeries.ILC2 },
	'ILCE-9M2': { name: 'A 9 II', type: sonySeries.ILC2 },
	'ILCE-1': { name: 'A 1', type: sonySeries.ILC2 }
};
